import React from 'react'

function About() {
    return (
        <React.Fragment>
            <h1 style={{textAlign: 'center'}}>About</h1>
            <div className="aboutDiv">
                <p>This is the To Do List, app version 1.0.0</p>
                <br></br>
                <p>React crash course</p>
                <p>The To Do items are being generated by http://jsonplaceholder.typicode.com/todos  using axios to call the http requests</p>
            </div>
            
        </React.Fragment>
    )
}


export default About;
